### ISSUE TITLE
Waybar location & Battery Icon Backgroun Fill Color

### ISSUE THREAD

**Issue by rmelendezz** [MubinMuhammad/MinimalSwayFX#1] opened 2024-04-18 06:36 UTC
Hi, first of all, thank you so much for sharing this awesome dots with all of us. 

OS: Asahi Fedora 39
I am running it on a m1 MacPro

I there a way I can fix the location of the waybar? If you see the following screenshot the bar is touching the top of my screen, this might be due to the screen resolution? also is it possible to fix the battery while being charge background color? The screenshot shows both of the questions I have

Thank you so much again!

![20240417_23h32m38s_grim](https://github.com/MubinMuhammad/MinimalSwayFX/assets/153709974/79eaf853-6d4a-42e1-b989-908833ddf3c1)

**Comment by MubinMuhammad** [comment] 2024-04-21 12:27
Sorry, It was actually a problem in my part, update your config to the latest version, the installation have been made easier with `install.sh` script. The old configs should be in ~/.config/{config_name}_bak folder. As of the problem you have mentioned, it should be fixed. Make sure that you've installed required dependencies mentioned in the repo (including the font).

And by default all the blurs, shadows and all of that cool stuff are turned off by default to make sure that the repo is compatible with Sway. If you want to have blur, shadows etc. go to line 120 in ~/.config/sway/config and change the effects to your liking!

Thanks for using MinimalSwayFX.

**Comment by rmelendezz** [comment] 2024-04-21 20:58
Thank you so much!

**Comment by MubinMuhammad** [comment] 2024-04-22 03:47
Closing, as the problem is solved.

**Closed by MubinMuhammad** 2024-04-22 03:47 UTC
